name: Build, test and deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: main

    steps:
      - uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0

      - name: Node pkg install
        run: npm install

      - name: Build
        env:
          SRC: ${{ vars.SRC }}
          TMP: ${{ vars.TMP }}
          DEST: ${{ vars.DEST }}
          URL: ${{ vars.URL }}
        run: |
          mkdir ${TMP}
          npx gulp build
          npx gulp test
  
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftps
          port: ${{ secrets.PORT }}
  
      # - name: Deploy
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER }}
      #     port: ${{ secrets.PORT }}
      #     key: ${{ secrets.KEY }}
      #     source: ${{ vars.DEST }}/*
      #     target: /var/www/${{ vars.HOSTNAME }}/public
      #     strip_components: 1
